package com.revature.models;

public enum Language {
	COMMON, DWARVISH, ELVISH, GIANT, GNOMISH, GOBLIN, HALFING, ORC, ABYSSAL, CELESTIAL, DEEPSPEECH, DRACONIC, INFERNAL, PRIMORDIAL, SYLVAN, UNDERCOMMON
}
